<?php

namespace Container8fLrd8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZjHm8giService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zjHm8gi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zjHm8gi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'orderInfoRepository' => ['privates', 'App\\Repository\\OrderInfoRepository', 'getOrderInfoRepositoryService', true],
        ], [
            'orderInfoRepository' => 'App\\Repository\\OrderInfoRepository',
        ]);
    }
}
