<?php

namespace Container8fLrd8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LkyesZFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LkyesZF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LkyesZF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'request' => ['privates', '.errored..service_locator.LkyesZF.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.LkyesZF": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
        ]);
    }
}
