<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8fLrd8x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8fLrd8x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8fLrd8x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8fLrd8x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8fLrd8x\App_KernelDevDebugContainer([
    'container.build_hash' => '8fLrd8x',
    'container.build_id' => 'ca158ab8',
    'container.build_time' => 1659072057,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8fLrd8x');
